esphome:
  name: sensorbox
  friendly_name: Sensorbox

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "" # Use your own key

ota:
  password: "" # Use your own ota password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensorbox Fallback Hotspot"
    password: "" # Use your own password

captive_portal:

# I2C Configuration for BMP180 and ADS1115
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: True

number:
  - platform: template
    name: "Präsenzsensor Ein-Verzögerung"
    id: praesenzsensor_delay_on
    min_value: 1
    max_value: 60
    step: 1
    initial_value: 1
    optimistic: true

  - platform: template
    name: "Präsenzsensor Aus-Verzögerung"
    id: praesenzsensor_delay_off
    min_value: 1
    max_value: 300
    step: 1
    initial_value: 160
    optimistic: true

binary_sensor:
  - platform: gpio
    device_class: motion
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    name: "Bewegungssensor"
      

  - platform: gpio
    device_class: motion
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
    name: "Präsenzmelder"
    filters:
      - delayed_on: !lambda "return id(praesenzsensor_delay_on).state * 1000;"
      - delayed_off: !lambda "return id(praesenzsensor_delay_off).state * 1000;"

ads1115:
  - address: 0x48

sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 2.048
    resolution: 16_BITS
    name: "MQ-2 Gassensor"
    id: mq_adc
    device_class: gas
    filters:
      - offset: 0.2248
      - multiply: 100
    unit_of_measurement: "%"
    update_interval: 1s
  
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 6.144
    resolution: 16_BITS
    name: "LDR Wert"
    id: ldr_adc
    filters:
      - lambda: "return (((x / 4095.0) * 6.144 * 1000.0) / (pow((1.0 - (x / 4095.0)), 0.8) * 5.0)*1000);"
    unit_of_measurement: "Lux"
    update_interval: 4s

  - platform: bmp085
    temperature:
      name: "BMP180 Temperature"
      id: "bmp085_temperature"
    pressure:
      name: "BMP180 Pressure"
    update_interval: 10s
  
  - platform: dht
    pin: GPIO13 
    model: DHT11
    temperature:
      name: "DHT11 Temperatur"
      id: "dht11_temperature"
    humidity:
      name: "DHT11 Luftfeuchtigkeit"
    update_interval: 10s

  - platform: template
    name: "Durchschnittstemperatur"
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 1
    lambda: |-
      return (id(dht11_temperature).state + id(bmp085_temperature).state) / 2.0;
    update_interval: 10s
    